### ISSUE TITLE
Handler fails to build on macOS.

### ISSUE THREAD

**Issue by OmniBlade** [backtrace-labs/crashpad#10]
Upstream minichromium now sets OS_MAC instead of OS_MACOSX which handler_main.cc uses to gate the addition of the attachments support to the CrashReportExceptionHandler object.

**Comment by KrzaQ** [comment]
Thanks for reporting this, we will fix it. As a work around, for the time being please use an older version of mini_chromium.

**Comment by KrzaQ** [comment]
We have updated the fork to build on the newest MacOS and added CMake build files to make building easier. Closing. Feel free to post if the issue persists with the new fork.
