### ISSUE TITLE
help!help!help! Windows compile error .

### ISSUE THREAD

**Issue by wustwg** [backtrace-labs/crashpad#12]
I try to compile crashpad and folow the steps in https://docs.bugsplat.com/introduction/getting-started/integrations/cross-platform/crashpad/how-to-build-google-crashpad , but the compile error occurred:

> D:\code\crashpad\crashpad>gn gen out/Default                                                                                        Done. Made 93 targets from 27 files in 13475ms                                                                                      
D:\code\crashpad\crashpad>ninja -C  out/Default                                                                                     ninja: Entering directory `out/Default'                                                                                             [1/514] STAMP obj/build/default_exe_manifest_win.stamp                                                                              FAILED: obj/build/default_exe_manifest_win.stamp                                                                                    python3 D:/code/crashpad/crashpad/third_party/mini_chromium/mini_chromium/build/win_helper.py stamp obj/build/default_exe_manifest_win.stamp                                                                                                                            CreateProcess failed: The system cannot find the file specified.                                                                    [2/514] STAMP obj/snapshot/snapshot_test_ios_data.stamp                                                                             FAILED: obj/snapshot/snapshot_test_ios_data.stamp                                                                                   python3 D:/code/crashpad/crashpad/third_party/mini_chromium/mini_chromium/build/win_helper.py stamp obj/snapshot/snapshot_test_ios_data.stamp                                                                                                                           CreateProcess failed: The system cannot find the file specified.                                                                    ninja: fatal: ReadFile: 句柄无效。

I have been  stucked at here more than one day, can you help me ? Thank you.

**Comment by KrzaQ** [comment]
Hi, @wustwg, I'm afraid this is a repository with [Backtrace](https://backtrace.io)'s changes, and is not intended for use with any other instructions.

That being said, you're entering the correct commands, so in your place I'd try building vanilla crashpad (directly from [Google's instructions](https://chromium.googlesource.com/crashpad/crashpad/+/HEAD/doc/developing.md)) and ensure that `depot_tools` is the first thing in your PATH. Maybe you're using the incorrect binary of `ninja` or `python3` and that causes you problems.
