### ISSUE TITLE
Add tags to publish backtrace-crashpad to homebrew

### ISSUE THREAD

**Issue by shraddhaarora** [backtrace-labs/crashpad#42]
Hi, we at Postman are willing to publish crashpad to homebrew, and since this is a well maintained fork of crashpad which is also CMake compatible, it would be great if this fork could be published to homebrew. However, one of the changes required for publishing this fork is adding tags and stable releases recommended by you guys so that it falls under the regulations of Homebrew.

Any responses or suggestions appreciated!

**Comment by shraddhaarora** [comment]
cc @KrzaQ

**Comment by konraddysput** [comment]
hi @shraddhaarora 

Thank you for contacting us. Unfortunately, we need a few days more to reply to your answer - our team is US-based. Sorry for the inconvenience.

**Comment by shraddhaarora** [comment]
Hi @konraddysput , thanks for letting us know. Awaiting your response!

**Comment by jviotti** [comment]
Thanks @konraddysput ! This would be very convenient for us too.

**Comment by rick-bt** [comment]
Hi @shraddhaarora, @jviotti - Yes, we're happy to add tags and releases. Even more happy to see this in homebrew. :) We have some cool improvements here for macos, like handling attachments.

I want to ensure that we approach this correctly to keep the projected future of our fork aligned with Chromium, and I also have a concern that the output executable is not versioned. We're still processing these concerns now, but I expect we will tag & release shortly.

**Comment by jviotti** [comment]
Hey @rick-bt , thanks for the response. That'd be great. We are eager to use these additional features at Postman. Let us know as soon as you have published an initial version and we will attempt to send a PR to Homebrew (we are already working on having a Formula ready on our internal Tap)

**Comment by rick-bt** [comment]
Hi @jviotti, @shraddhaarora - We've tagged as 0.1.0.
Cheers,
Rick

**Comment by jviotti** [comment]
Thanks a lot @rick-bt ! Feel free to close this issue if you want.

**Comment by shraddhaarora** [comment]
Thanks @rick-bt !
