### ISSUE TITLE
How do I build an Xcode project for macOS？

### ISSUE THREAD

**Issue by snilwx** [backtrace-labs/crashpad#44]

**Comment by rick-bt** [comment]
Hi @snilwx - can you provide detail on where the build fails for you? What documentation are you following?

**Comment by snilwx** [comment]
> Hi @snilwx - can you provide detail on where the build fails for you? What documentation are you following?

I've looked at all the documentation, but nothing says how to compile crashpad into framework for macOS.

**Comment by alecazam** [comment]
There's no framework.  You use Cmake to build an xcode project, and then have to include that.  That builds a lib and you link to that.   Only Apple puts the time in to build frameworks, but Crashpad is from Google.

**Comment by rick-bt** [comment]
+1  Thank you Alec.

**Comment by snilwx** [comment]
Thank you very much Alec.
