### ISSUE TITLE
Backtrace crashpad doesn't allow annotations to be added after StartHandler, also doesn't cleanup threads.

### ISSUE THREAD

**Issue by alecazam** [backtrace-labs/crashpad#45]
Our team just integrated Backtrace and crashpad, but the api requires all annotations to be passed to StartHandler.  There's no way to pass more, there's no StopHandler, and calling StartHandler repeatedly allows us to specify more annotations, but ends up generating 8x more threads and a process every time we call it.  Even calling delete on CrashpadClient doesn't cleanup threads.   

I don't understand how this is supposed to work.  Most apps don't have all the annotations at the very start of main, and don't know where they are going to crash at startup.  We generate them over the course of our initialization.  Why is thread cleanup so poor, and why isn't there an api for doing this?

```
bool ReInitializeCrashpad()
{
	// only way to stop the old one is to delete CrashPadClient?
	delete sClient;
	sClient = nullptr;

	// create a new one
	auto& params = sParams;
	sClient = new crashpad::CrashpadClient();
	bool rc = sClient->StartHandler( params.handler, params.db, params.db, params.endpoint, params.annotations, params.arguments, true, true );
	if ( !sClient || !rc )
	{
		return false;
	}
	return sClient->WaitForHandlerStart( 50000 );
}
```

**Comment by alecazam** [comment]
The sample/example app is so far removed from what a real application does.  It's a main that calls StartHandler with some fixed annotations, and then crashes.   Our game needs to Init, and then add attributes/annotation about the current level.  And I can think of many apps that need to add runtime annotations.  So this can't be locked up in a single StartHandler call.  

We could register the keys at StartHandler, and then data later.  But StartHandler just seems to copy the annotations map passed in to a data member.  So that squashes that idea.  I don't know how this API is usable in production.

**Comment by alecazam** [comment]
Tried this too, to no avail.  According to Google's docs on crashpad, we're supposed to be the client.  And supposed to be able to set name:value pairs into the CrashpadInfo.  But this annotation list is null even though we passed annotations to StartHandler.   Calling AnnotationList::Register() fixes the null list, but I have no idea if this new list goes out on crashes yet.

```
static void UpdateCrashpadInfo()
{
	// This is already set into CrashpadInfo

	AnnotationList* annotationsList = AnnotationList::Get();
	// if ( !annotationsList ) return; <- returns here
	if ( !annotationsList ) 
		annotationsList = AnnotationList::Register();

	for (const auto& it : sParams.annotations )
	{
		Annotation annotation( Annotation::Type::kString, it.first.c_str(), (void*)it.second.c_str() );
		annotation.SetSize( it.second.length() + 1 ); // include terminator
		annotationsList->Add( &annotation );
	}
}
```

And then this has no data, no lists or anything in it even after calling StartHandler with annotations in a map.  The annotations passed to this just seem to be collected and then passed off as command line args to a process that creates 6 unnamed threads.  We aren't a browser, and need to specify keys from our app.  We don't need process protections AFAIK.  We just need the stack dumped out.   

```
CrashpadInfo* crashpadInfo = CrashpadInfo::GetCrashpadInfo();
```

**Comment by konraddysput** [comment]
hi @alecazam 

I believe we follow some rules/directions that Google has/had for Craspad. So far we didn't have a real use case when we needed to extend annotations for native reports. The reason behind it is because 99% of the time when we were talking about something like that, we ended up with extending attributes instead. 

This is internal Crashpad limitations, that you can also expand in the code. Maybe it would be better to switch to attributes instead?

**Comment by alecazam** [comment]
Sample code or snippet for that?  This needs to be in the examples, so I’m not guessing.  The Google docs say nothing of attributes.  And the GitHub page doesn’t show anything.   But I have obviously seen them since they are in our reports.

Annotations are an attribute, so again I don't understand why they are locked down for all time to the crash process.   It's going to halt the main process when a crash occurs.  Fine, but how do we send more data to that process to write out.  

"Optional Annotations
You can use the annotations map to set additional attributes. Attributes allow you to embed relevant context into each crash report and can be any data point you choose. Examples include version, directx.version, graphics.card, etc. You can find more information on attributes in the product guide."

**Comment by konraddysput** [comment]
```
Annotations are an attribute, so again I don't understand why they are locked down for all time to the crash process. It's going to halt the main process when a crash occurs. Fine, but how do we send more data to that process to write out.
```

it depends on how you understand and interpret the data. Annotations is a non-structured objects that can store anything. Attributes is key:value pair that can store primitive values. 



The way how we include a new attribute in crashpad is demonstrated below. The purpose of this response is to share knowledge. Later we can plan to add more intuitive example. Here is a code available in our backtrace-android repository

```
const std::lock_guard<std::mutex> lock(attribute_synchronization);
    crashpad::CrashpadInfo *info = crashpad::CrashpadInfo::GetCrashpadInfo();
    crashpad::SimpleStringDictionary *annotations = info->simple_annotations();
    if (!annotations) {
        annotations = new crashpad::SimpleStringDictionary();
        info->set_simple_annotations(annotations);
    }

    jboolean isCopy;
    const char *crashpadKey = env->GetStringUTFChars(key, &isCopy);
    const char *crashpadValue = env->GetStringUTFChars(value, &isCopy);
    if (crashpadKey && crashpadValue)
        annotations->SetKeyValue(crashpadKey, crashpadValue);

    env->ReleaseStringUTFChars(key, crashpadKey);
    env->ReleaseStringUTFChars(value, crashpadValue);
}
```

and the code works correctly for us on multiple OSes

**Comment by alecazam** [comment]
Seems like the same thing my code does but not really using the API as intended (f.e. AnnotationList::Register())?   And we're just using C++, not java.  So yes, we'll try the AnnotationList and test to see that it ends up on Backtrace.   Is there any diference between the simple annotations and the annotation list.  The simple annotations seemed hardcoded to 256B key, 256B value, and 64 of them.  That's a bit limiting.  

So the annotations/attributes sent to StartHandler are frozen at the process level, and the ones in the CrashpadInfo are module specific.

**Comment by alecazam** [comment]
Also naming of the process threads, or any threads created by crashpad.

![image](https://github.com/backtrace-labs/crashpad/assets/3750359/5410eb6f-a0db-45a1-b80f-f415dc19cf5e)

**Comment by alecazam** [comment]
Appears the AnnotationsList doesn't appear in the crash report.  So that seems ignored.  So now having to implement the support using the simple_annotations().  How is this not documented?   The simple_annotations() worked, but is limited as per above.

Thanks for the help.  Our thread counts are back to normal, and the dynamic attributes that we needed are now present.
