### ISSUE TITLE
An abort() or _purecall() on main native thread causes unhandled exception "0x40000015: %hs"

### ISSUE THREAD

**Issue by mike-malburg** [backtrace-labs/crashpad#9]
When an `abort()` or `_purecall()` is done on the main thread of a native application, we are getting an unhandled exception in our dmp files: `0x40000015: %hs` .  This is obscuring the actual underlying issue that caused the crash in our application.

This seems to be originating from this `CaptureContext` call:
https://github.com/backtrace-labs/crashpad/blob/7b9686bb65af618daa5dd06d140c849b51884cb4/client/crashpad_client_win.cc#L201

### From test app
![stacktrace](https://user-images.githubusercontent.com/62569405/148122717-73384965-055a-48af-a0a9-1573e24de981.png)

**Comment by daveorourke** [comment]
Note that 0x40000015 is `STATUS_FATAL_APP_EXIT`, which is the exception code that CrashPad uses here: 
https://github.com/backtrace-labs/crashpad/blob/backtrace/client/crashpad_client_win.cc#L212

> This is obscuring the actual underlying issue that caused the crash in our application.

Isn't the crash just a little further down the call stack?  If you skip past the CrashPad handling, it looks like the call stack has the line with the `abort()` call, which triggers the CrashPad handler.
![image](https://user-images.githubusercontent.com/8958899/148268454-bb070d34-d9aa-4d90-95ad-e662c435d388.png)
https://github.com/TechSmith/BackTrace-Support-Issues/blob/main/CrashpadCrash16984/src/TestBacktraceCrash/TestApp.cpp#L76

**Comment by BillHoag** [comment]
@vlussenburg Is this closed with a fix? If so, should updated binaries be posted [here](http://get.backtrace.io/crashpad/builds/)?

**Comment by vlussenburg** [comment]
More closed due to inactivity. We also merged all the upstream changing in, so we’d have to verify is this is still an issue.

Currently, we recommend building from source using cmake, or grabbing binaries from our Github Actions daily builds:
https://github.com/backtrace-labs/crashpad/actions/runs/3373865545
